In [1]:
import re
import requests
import bs4

# Web scrapping

In [2]:
url = "https://es.wikipedia.org/wiki/Canis_familiaris"
response = requests.get(url)
content = response.content
html = bs4.BeautifulSoup(content, "html.parser")
text = html.get_text()
text

'\n\n\n\nCanis familiaris - Wikipedia, la enciclopedia libre\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nIr al contenido\n\n\n\n\n\n\n\nMenú principal\n\n\n\n\n\nMenú principal\nmover a la barra lateral\nocultar\n\n\n\n\t\tNavegación\n\t\n\n\nPortadaPortal de la comunidadActualidadCambios recientesPáginas nuevasPágina aleatoriaAyudaDonacionesNotificar un error\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nBuscar\n\n\n\n\n\n\n\n\n\n\n\nBuscar\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nCrear una cuenta\n\nAcceder\n\n\n\n\n\n\n\n\nHerramientas personales\n\n\n\n\n\n Crear una cuenta Acceder\n\n\n\n\n\n\t\tPáginas para editores desconectados más información\n\n\n\nContribucionesDiscusión\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nContenidos\nmover a la barra lateral\nocultar\n\n\n\n\nInicio\n\n\n\n\n\n1Características\n\n\n\nAlternar subsección Características\n\n\n\n\n\n1.1Diferencias respecto a otros cánidos\n\n\n\n\n\n\n\n1.2Anatomía

In [3]:
text = re.sub(r"\n+", "\n", text)
text = re.sub(r"\[\d+\]\u200b", "", text)
text

'\nCanis familiaris - Wikipedia, la enciclopedia libre\nIr al contenido\nMenú principal\nMenú principal\nmover a la barra lateral\nocultar\n\t\tNavegación\n\t\nPortadaPortal de la comunidadActualidadCambios recientesPáginas nuevasPágina aleatoriaAyudaDonacionesNotificar un error\nBuscar\nBuscar\nCrear una cuenta\nAcceder\nHerramientas personales\n Crear una cuenta Acceder\n\t\tPáginas para editores desconectados más información\nContribucionesDiscusión\nContenidos\nmover a la barra lateral\nocultar\nInicio\n1Características\nAlternar subsección Características\n1.1Diferencias respecto a otros cánidos\n1.2Anatomía externa\n1.2.1Pelaje\n1.2.2Cola\n1.3Aparato locomotor\n1.4Sentidos\n1.4.1Vista\n1.4.2Oído\n1.4.3Olfato\n1.4.4Gusto\n1.4.5Tacto\n2Comportamiento\nAlternar subsección Comportamiento\n2.1Inteligencia\n2.2Socialización\n2.3Problemas de comportamiento o anormales\n2.4Gruñido\n3Salud\nAlternar subsección Salud\n3.1Enfermedades\n3.2Reproducción\n3.3Castración y esterilización\n3.4Ali

In [4]:
import nltk

In [5]:
text = "mi gato es blanco. tu perro es bonito"

In [6]:
nltk.sent_tokenize(text)

['mi gato es blanco.', 'tu perro es bonito']

In [7]:
nltk.word_tokenize(text)

['mi', 'gato', 'es', 'blanco', '.', 'tu', 'perro', 'es', 'bonito']

In [8]:
text = "mi amigo es de los EE.UU. Los beneficios fueron de 2.3 millones de euros"

In [9]:
nltk.sent_tokenize(text)

['mi amigo es de los EE.UU.', 'Los beneficios fueron de 2.3 millones de euros']

In [10]:
nltk.word_tokenize(text)

['mi',
 'amigo',
 'es',
 'de',
 'los',
 'EE.UU',
 '.',
 'Los',
 'beneficios',
 'fueron',
 'de',
 '2.3',
 'millones',
 'de',
 'euros']

In [11]:
response = requests.get(url)
content = response.content
html = bs4.BeautifulSoup(content, "html.parser")
text = html.get_text()
text = re.sub(r"\n+", "\n", text)
text = re.sub(r"\[\d+\]\u200b", "", text)
text

'\nCanis familiaris - Wikipedia, la enciclopedia libre\nIr al contenido\nMenú principal\nMenú principal\nmover a la barra lateral\nocultar\n\t\tNavegación\n\t\nPortadaPortal de la comunidadActualidadCambios recientesPáginas nuevasPágina aleatoriaAyudaDonacionesNotificar un error\nBuscar\nBuscar\nCrear una cuenta\nAcceder\nHerramientas personales\n Crear una cuenta Acceder\n\t\tPáginas para editores desconectados más información\nContribucionesDiscusión\nContenidos\nmover a la barra lateral\nocultar\nInicio\n1Características\nAlternar subsección Características\n1.1Diferencias respecto a otros cánidos\n1.2Anatomía externa\n1.2.1Pelaje\n1.2.2Cola\n1.3Aparato locomotor\n1.4Sentidos\n1.4.1Vista\n1.4.2Oído\n1.4.3Olfato\n1.4.4Gusto\n1.4.5Tacto\n2Comportamiento\nAlternar subsección Comportamiento\n2.1Inteligencia\n2.2Socialización\n2.3Problemas de comportamiento o anormales\n2.4Gruñido\n3Salud\nAlternar subsección Salud\n3.1Enfermedades\n3.2Reproducción\n3.3Castración y esterilización\n3.4Ali

In [12]:
sentences = nltk.sent_tokenize(text, language = "spanish")

In [13]:
sentences[-5:]

['Biodiversity Heritage Library bibliography for Canis lupus familiaris\nDogs in the Ancient World, artículo sobre la historia de los perros\nVértebras del perro\nControl de autoridades\nProyectos Wikimedia\n Datos: Q20717272\n Diccionario: perro\n Especies: Canis lupus familiaris\nIdentificadores\nAAT: 300250130\nBases de datos taxonómicas\nGBIF: 5219200\niNaturalist: 47144\nITIS: 183815\nNCBI: 9615\nPaleobiology Database: 104153\nWoRMS: 1461482\nZoobank: 05C23FE8-F45D-4EA6-A309-46864DE24097\n Datos: Q20717272\n Diccionario: perro\n Especies: Canis lupus familiaris\nObtenido de «https://es.wikipedia.org/w/index.php?title=Canis_familiaris&oldid=158719337»\nCategorías: Animales domesticadosPerrosCánidos (Canidae) no amenazadosAnimales descritos en 1758Categorías ocultas: Wikipedia:Páginas con referencias con et al.',
 'implícito en los autoresWikipedia:Páginas con referencias sin URL y con fecha de accesoWikipedia:Artículos con enlaces externos rotosWikipedia:Páginas con enlaces mágicos

# match case

In [14]:
import random

In [15]:
user_response = input("Escoge piedra, papel o tijera")
pc_response = random.choice(["piedra", "papel", "tijera"])

match (user_response, pc_response):

    case ("piedra", "tijera"): ganador = "usuario"
    case ("piedra", "papel"): ganador = "pc"
    case ("papel", "piedra"): ganador = "usuario"
    case ("papel", "tijera"): ganador = "pc"
    case ("tijera", "papel"): ganador = "usuario"
    case ("tijera", "piedra"): ganador = "pc"
    case _: ganador = "empate"

print(f"Tu elección fue {user_response} y la mía fue {pc_response}, así que el ganador es {ganador}")

Escoge piedra, papel o tijera piedra


Tu elección fue piedra y la mía fue piedra, así que el ganador es empate


In [16]:
user_response = input("Escoge piedra, papel o tijera")
pc_response = random.choice(["piedra", "papel", "tijera"])

match (user_response, pc_response):
    case ('piedra', 'tijera') | ('tijera', 'papel') | ('papel', 'piedra'):
        resultado = f'Gana usuario con {user_response}!'
    case ('tijera', 'piedra') | ('papel', 'tijera') | ('piedra', 'papel'):
        resultado = f'Gana máquina con {pc_response}!'
    case _:
        resultado = f'Empate!'

print(resultado, user_response, pc_response)

Escoge piedra, papel o tijera papel


Empate! papel papel


# Generador de contraseñas

In [17]:
def generate_password():
    password = "123456"
    return password

generate_password()

'123456'

In [18]:
names = lambda obj: print([name for name in dir(obj) if name[0] != "_"])

In [19]:
names(random)

['BPF', 'LOG4', 'NV_MAGICCONST', 'RECIP_BPF', 'Random', 'SG_MAGICCONST', 'SystemRandom', 'TWOPI', 'betavariate', 'choice', 'choices', 'expovariate', 'gammavariate', 'gauss', 'getrandbits', 'getstate', 'lognormvariate', 'normalvariate', 'paretovariate', 'randbytes', 'randint', 'random', 'randrange', 'sample', 'seed', 'setstate', 'shuffle', 'triangular', 'uniform', 'vonmisesvariate', 'weibullvariate']


In [20]:
random.choices(list("aeiou"), k = 2)

['a', 'i']

In [21]:
def generate_password(length = 8):
    alphabet = "abcdefghijk"
    password = random.choices(list(alphabet), k = length)
    password = "".join(password)
    return password

generate_password(4)

'jggj'

In [22]:
"".join(["hola", "adiós", "python"])

'holaadióspython'

In [23]:
import string

In [24]:
names(string)

['Formatter', 'Template', 'ascii_letters', 'ascii_lowercase', 'ascii_uppercase', 'capwords', 'digits', 'hexdigits', 'octdigits', 'printable', 'punctuation', 'whitespace']


In [25]:
string.digits

'0123456789'

In [26]:
string.ascii_letters

'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'

In [27]:
string.ascii_lowercase

'abcdefghijklmnopqrstuvwxyz'

In [28]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [29]:
string.printable

'0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~ \t\n\r\x0b\x0c'

In [30]:
def generate_password(length = 8, format = "all"):
    """ Genera un password de la longitud indicada y considerando el tipo
    de caracteres indicado:
    * "txt": Letras mayusculas y minúsculas
    * "number": Números
    * "txt_number": Letras mayúsculas, minúsculas y números
    * "all": Letras mayúsculas, minúsculas, números y caracteres especiales
    """
    match format:
        case "txt": alphabet = string.ascii_letters
        case "number": alphabet = string.digits
        case "txt_number": alphabet = string.ascii_letters + string.digits
        case "all": alphabet = string.ascii_letters + string.digits + "_%?"
        case _: alphabet = "aeiou"

    password = random.choices(list(alphabet), k = length)
    password = "".join(password)
    return password

generate_password(length = 16)

'buk1ct1DjoHPOpxk'

In [31]:
alphabet = string.ascii_letters
alphabet

'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'

# NumPy

In [32]:
a = [2, 4, 6, 8]

In [33]:
# a + 1

In [34]:
b = [1, 2, 3, 4]

In [35]:
a + b

[2, 4, 6, 8, 1, 2, 3, 4]

In [36]:
a * 2

[2, 4, 6, 8, 2, 4, 6, 8]

In [37]:
a = [   [1, 2, 3],    [4, 5, 6] ]
a

[[1, 2, 3], [4, 5, 6]]

In [38]:
a = [2, 4, 6, 8]

In [39]:
print(a)
print(b)

[2, 4, 6, 8]
[1, 2, 3, 4]


In [40]:
import numpy as np

In [41]:
names(np)

['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', 'abs', 'absolute', 'add', 'add_docstring', 'add_newdoc', 'add_newdoc_ufunc', 'all', 'allclose', 'alltrue', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arctanh', 'argmax', 'argmin', 'argpartition', 'argsort', 'argwhere', 'around', 'array', 'array2string', 'array_equal', 'array_equiv', 'array_repr', 'array_split', 'array_str', 'asanyarray', 'asarray'

In [42]:
a = np.array(a)
a

array([2, 4, 6, 8])

In [43]:
b = np.array(b)
b

array([1, 2, 3, 4])

In [44]:
a + b

array([ 3,  6,  9, 12])

In [45]:
a

array([2, 4, 6, 8])

In [46]:
type(a)

numpy.ndarray

In [47]:
len(a)

4

In [48]:
a.dtype

dtype('int32')

In [49]:
[1, 3, True, "hola", [2, 4]]

[1, 3, True, 'hola', [2, 4]]

In [50]:
a

array([2, 4, 6, 8])

In [51]:
a.ndim

1

In [52]:
a.shape

(4,)

1. Extraer datos de un array
1. Aplicar funciones a un array

In [53]:
b = np.array([[2, 4, 6], [1, 2, 3]])
b

array([[2, 4, 6],
       [1, 2, 3]])

In [54]:
b.dtype

dtype('int32')

In [55]:
b.ndim

2

In [56]:
b.shape

(2, 3)

In [57]:
np.arange(2, 7)

array([2, 3, 4, 5, 6])

In [58]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [59]:
np.arange(10, 24, 3)

array([10, 13, 16, 19, 22])

In [60]:
np.linspace(10, 20, 6)

array([10., 12., 14., 16., 18., 20.])

In [61]:
np.linspace(10, 20, 17)

array([10.   , 10.625, 11.25 , 11.875, 12.5  , 13.125, 13.75 , 14.375,
       15.   , 15.625, 16.25 , 16.875, 17.5  , 18.125, 18.75 , 19.375,
       20.   ])

In [62]:
names(random)

['BPF', 'LOG4', 'NV_MAGICCONST', 'RECIP_BPF', 'Random', 'SG_MAGICCONST', 'SystemRandom', 'TWOPI', 'betavariate', 'choice', 'choices', 'expovariate', 'gammavariate', 'gauss', 'getrandbits', 'getstate', 'lognormvariate', 'normalvariate', 'paretovariate', 'randbytes', 'randint', 'random', 'randrange', 'sample', 'seed', 'setstate', 'shuffle', 'triangular', 'uniform', 'vonmisesvariate', 'weibullvariate']


In [63]:
names(np.random)

['BitGenerator', 'Generator', 'MT19937', 'PCG64', 'PCG64DXSM', 'Philox', 'RandomState', 'SFC64', 'SeedSequence', 'beta', 'binomial', 'bit_generator', 'bytes', 'chisquare', 'choice', 'default_rng', 'dirichlet', 'exponential', 'f', 'gamma', 'geometric', 'get_bit_generator', 'get_state', 'gumbel', 'hypergeometric', 'laplace', 'logistic', 'lognormal', 'logseries', 'mtrand', 'multinomial', 'multivariate_normal', 'negative_binomial', 'noncentral_chisquare', 'noncentral_f', 'normal', 'pareto', 'permutation', 'poisson', 'power', 'rand', 'randint', 'randn', 'random', 'random_integers', 'random_sample', 'ranf', 'rayleigh', 'sample', 'seed', 'set_bit_generator', 'set_state', 'shuffle', 'standard_cauchy', 'standard_exponential', 'standard_gamma', 'standard_normal', 'standard_t', 'test', 'triangular', 'uniform', 'vonmises', 'wald', 'weibull', 'zipf']


In [64]:
np.random.randint(4, 14)

7

In [65]:
np.random.randint(4, 14, size = 7)

array([11, 10, 12,  9, 12, 10, 13])

In [66]:
np.random.randint(4, 14, size = (3, 5))

array([[ 6,  9,  8, 13, 12],
       [ 6, 12,  5,  8,  9],
       [13, 10,  8,  7, 11]])

In [67]:
np.random.randint(4, 14, size = (3, 4, 2))

array([[[ 9,  5],
        [ 7,  7],
        [ 8, 11],
        [11, 10]],

       [[ 7, 10],
        [ 9, 11],
        [ 6,  4],
        [ 9,  4]],

       [[ 4,  8],
        [11,  9],
        [13,  9],
        [ 4, 12]]])

In [68]:
np.random.random(size = 4)

array([0.37398219, 0.83503414, 0.30266013, 0.81662182])

In [69]:
np.random.random(size = (5, 3))

array([[0.88994139, 0.61731379, 0.15118509],
       [0.99199064, 0.10915837, 0.25632719],
       [0.52119839, 0.19961177, 0.38886638],
       [0.19326397, 0.35486097, 0.88041551],
       [0.44551715, 0.19727   , 0.86192378]])

In [70]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [71]:
a.shape

(24,)

In [72]:
a.reshape((4, 6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [73]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [74]:
#a.reshape((3, 17))

In [75]:
np.reshape(a, newshape = (24, 1))

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [76]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [77]:
a.reshape((1, 24))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23]])

In [78]:
a = np.arange(4)

In [79]:
a

array([0, 1, 2, 3])

In [80]:
b = a.reshape(1, 4)
b

array([[0, 1, 2, 3]])

In [81]:
a.ndim

1

In [82]:
b.ndim

2

In [83]:
a.shape

(4,)

In [84]:
b.shape

(1, 4)

In [85]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [86]:
a.reshape((1, 24))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23]])

In [87]:
a.reshape((24, 1))

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [88]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [89]:
a.reshape(1, 24, 1)

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]]])

# Selección de valores

In [90]:
a = np.arange(10, 16)
a

array([10, 11, 12, 13, 14, 15])

In [91]:
a[0]

10

In [92]:
a[5]

15

In [93]:
a[-1]

15

In [94]:
a[2:4]

array([12, 13])

In [95]:
a[-4:4]

array([12, 13])

In [96]:
a[4:2]

array([], dtype=int32)

In [97]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
a[7:2:-1]

array([7, 6, 5, 4, 3])

In [99]:
a = np.arange(10, 22).reshape(3, 4)
a

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [100]:
a[2, 1]

19

In [101]:
b = list(range(10))
b

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [102]:
b[2:5]

[2, 3, 4]

In [103]:
b[2:]

[2, 3, 4, 5, 6, 7, 8, 9]

In [104]:
b[:4]

[0, 1, 2, 3]

In [105]:
b[:]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [106]:
a

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [107]:
a[-1]   # Equivalente a a[-1, :] solo por los ":" están a la derecha

array([18, 19, 20, 21])

In [108]:
a[0, :]

array([10, 11, 12, 13])