In [49]:
import re
import requests
import bs4

# Web scrapping

In [50]:
url = "https://es.wikipedia.org/wiki/Canis_familiaris"
response = requests.get(url)
content = response.content
html = bs4.BeautifulSoup(content, "html.parser")
text = html.get_text()
text

'\n\n\n\nCanis familiaris - Wikipedia, la enciclopedia libre\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nIr al contenido\n\n\n\n\n\n\n\nMenú principal\n\n\n\n\n\nMenú principal\nmover a la barra lateral\nocultar\n\n\n\n\t\tNavegación\n\t\n\n\nPortadaPortal de la comunidadActualidadCambios recientesPáginas nuevasPágina aleatoriaAyudaDonacionesNotificar un error\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nBuscar\n\n\n\n\n\n\n\n\n\n\n\nBuscar\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nCrear una cuenta\n\nAcceder\n\n\n\n\n\n\n\n\nHerramientas personales\n\n\n\n\n\n Crear una cuenta Acceder\n\n\n\n\n\n\t\tPáginas para editores desconectados más información\n\n\n\nContribucionesDiscusión\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nContenidos\nmover a la barra lateral\nocultar\n\n\n\n\nInicio\n\n\n\n\n\n1Características\n\n\n\nAlternar subsección Características\n\n\n\n\n\n1.1Diferencias respecto a otros cánidos\n\n\n\n\n\n\n\n1.2Anatomía

In [51]:
text = re.sub(r"\n+", "\n", text)
text = re.sub(r"\[\d+\]\u200b", "", text)
text

'\nCanis familiaris - Wikipedia, la enciclopedia libre\nIr al contenido\nMenú principal\nMenú principal\nmover a la barra lateral\nocultar\n\t\tNavegación\n\t\nPortadaPortal de la comunidadActualidadCambios recientesPáginas nuevasPágina aleatoriaAyudaDonacionesNotificar un error\nBuscar\nBuscar\nCrear una cuenta\nAcceder\nHerramientas personales\n Crear una cuenta Acceder\n\t\tPáginas para editores desconectados más información\nContribucionesDiscusión\nContenidos\nmover a la barra lateral\nocultar\nInicio\n1Características\nAlternar subsección Características\n1.1Diferencias respecto a otros cánidos\n1.2Anatomía externa\n1.2.1Pelaje\n1.2.2Cola\n1.3Aparato locomotor\n1.4Sentidos\n1.4.1Vista\n1.4.2Oído\n1.4.3Olfato\n1.4.4Gusto\n1.4.5Tacto\n2Comportamiento\nAlternar subsección Comportamiento\n2.1Inteligencia\n2.2Socialización\n2.3Problemas de comportamiento o anormales\n2.4Gruñido\n3Salud\nAlternar subsección Salud\n3.1Enfermedades\n3.2Reproducción\n3.3Castración y esterilización\n3.4Ali

In [1]:
import nltk

In [2]:
text = "mi gato es blanco, tu perro es bonito"

# Match case

In [12]:
import random

In [9]:
user_response = "piedra"
pc_response = "papel"

match (user_response, pc_response):

    case("piedra", "tijera"): ganador = "usuario"
    case("piedra", "papel"): ganador = "pc"
    case("papel", "piedra"): ganador = "usuario"
    case("papel", "tijera"): ganador = "pc"
    case("tijera", "papel"): ganador = "usuario"
    case("tijera", "piedra"): ganador = "pc"
    case _: ganador = "empate"

print(f"Tu elección fue {user_response} y la mia fue {pc_response}, asi que el ganador es {ganador}")

Tu elección fue piedra y la mia fue papel, asi que el ganador es pc


In [13]:
user_response = input("Escoge piedra, papel o tijera") 
pc_response = random.choice(["piedra", "papel", "tijera"]) 

match (user_response, pc_response): 
    case ('piedra', 'tijera') | ('tijera', 'papel') | ('papel', 'piedra'): 
        resultado = f'Gana usuario con {user_response}!' 
    case ('tijera', 'piedra') | ('papel', 'tijera') | ('piedra', 'papel'): 
        resultado = f'Gana máquina con {pc_response}!' 
    case _: 
        resultado = f'Empate!' 
        
print(resultado, user_response, pc_response)

Escoge piedra, papel o tijera piedra


Gana máquina con papel! piedra papel


# Generador de contraseñas

In [14]:
def generate_password():
    password = "123456"
    return password

generate_password()

'123456'

In [15]:
names = lambda obj: print([name for name in dir(obj) if name[0] != "_"])

In [16]:
names(random)

['BPF', 'LOG4', 'NV_MAGICCONST', 'RECIP_BPF', 'Random', 'SG_MAGICCONST', 'SystemRandom', 'TWOPI', 'betavariate', 'choice', 'choices', 'expovariate', 'gammavariate', 'gauss', 'getrandbits', 'getstate', 'lognormvariate', 'normalvariate', 'paretovariate', 'randbytes', 'randint', 'random', 'randrange', 'sample', 'seed', 'setstate', 'shuffle', 'triangular', 'uniform', 'vonmisesvariate', 'weibullvariate']


In [18]:
random.choices(list("aeiou"), k = 2)

['e', 'o']

In [21]:
def generate_password():
    alphabet = "abcdefghijk"
    password = random.choices(list(alphabet), k = 8)
    password = "".join(password)
    return password

generate_password()

'cibedijg'

In [20]:
"*".join(["hola", "adios", "python"])

'hola*adios*python'

In [24]:
import string

In [25]:
names(string)

['Formatter', 'Template', 'ascii_letters', 'ascii_lowercase', 'ascii_uppercase', 'capwords', 'digits', 'hexdigits', 'octdigits', 'printable', 'punctuation', 'whitespace']


In [26]:
string.digits

'0123456789'

In [27]:
string.ascii_letters

'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'

In [28]:
string.ascii_lowercase

'abcdefghijklmnopqrstuvwxyz'

In [29]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [30]:
string.printable

'0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~ \t\n\r\x0b\x0c'

In [41]:
def generate_password(length = 8, format = "all"):
    """Genera un password de la longitud indicada y considerando el tipo de caracteres indicado:
    * "txt": Letras mayusculas y minusculas
    * "number": Números
    *"txt_number": Letras mayúsculas, minúsculas y números
    * "all": Letras mayúsculas, minúsculas, números y caracteres especiales
    """

    alphabet = ""
    if format == "txt":
        alphabet = string.ascii_letters
    elif format == "number":
        alphabet = string.digits
    elif format == "txt_number":
        alphabet = string.ascii_letters + string.digits
    elif format == "all":
        alphabet = string.printable

    password = random.choices(list(alphabet), k = length)
    password = "".join(password)
    return password

generate_password(length = 16, format = "txt_number")

'zbYXftan5lfPnLCl'

In [48]:
def generate_password(length = 8, format = "all"):
    """Genera un password de la longitud indicada y considerando el tipo de caracteres indicado:
    * "txt": Letras mayusculas y minusculas
    * "number": Números
    *"txt_number": Letras mayúsculas, minúsculas y números
    * "all": Letras mayúsculas, minúsculas, números y caracteres especiales
    """

    match format:
        case "txt": alphabet = string.ascii_letters
        case "number": alphabet = string.digits
        case "txt_number": alphabet = string.ascii_letters + string.digits
        case "all": alphabet = string.ascii_letters + string.digits + "_%?"
        case _: alphabet = "aeiou"

    password = random.choices(list(alphabet), k = length)
    password = "".join(password)
    return password

generate_password(length = 16, format = "txt_number")

'KhQcSO6LuAOZt2gQ'

# Stack Científico de Python

## NumPy (numeric Python)

In [52]:
#Nos provee de una clase nueva: Array numpy multidimensional (Array)

## Pandas

In [54]:
#Seties Pandas. Estructura unidimensional
#Dataframe Estructura bidimensional

#Pandas se construye sobre NumPy

## SciPy

In [56]:
#Scientific Python
#Orientada a la parte matemática
#Ofrece herramientas para uso de polinomios, álgebra lineal

## Matplotlib/Seaborn/Plotly/Pandas/Bokeh

In [59]:
#Visualización.
#Creación de gráficas
#Pandas tambien tiene funciones gráficas.
#Pandas y Seaborn usan por detrás Matplotlib

## Scikit learn

In [60]:
#no es una librería especializada. Pero sirve ya directamente para Machine Learning


## Tensor flow

In [61]:
#Libreria de google, especializada para la creación de redes neuronales

## NLTK

In [62]:
#Herramienta para tratamiento de textos

# NumPy

In [63]:
a = [2, 4, 6, 8]

In [64]:
# a +1

In [65]:
b = [1, 2, 3, 4]

In [66]:
a + b

[2, 4, 6, 8, 1, 2, 3, 4]

In [68]:
a * 2

[2, 4, 6, 8, 2, 4, 6, 8]

In [69]:
a = [ [1, 2, 3], [4, 5, 6] ]

In [70]:
print(a)
print(b)

[[1, 2, 3], [4, 5, 6]]
[1, 2, 3, 4]


In [75]:
a = [2, 4, 6, 8]
b = [1, 2, 3, 4]

In [76]:
print(a)
print(b)

[2, 4, 6, 8]
[1, 2, 3, 4]


In [71]:
import numpy as np

In [72]:
names(np)

['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', 'abs', 'absolute', 'add', 'add_docstring', 'add_newdoc', 'add_newdoc_ufunc', 'all', 'allclose', 'alltrue', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arctanh', 'argmax', 'argmin', 'argpartition', 'argsort', 'argwhere', 'around', 'array', 'array2string', 'array_equal', 'array_equiv', 'array_repr', 'array_split', 'array_str', 'asanyarray', 'asarray'

In [90]:
a = np.array(a) #Donde vemos un array, se trata de un array numPy multidimensional
a

array([2, 4, 6, 8])

In [89]:
b = np.array(b)
b

array([1, 2, 3, 4])

In [91]:
a + b 

array([ 3,  6,  9, 12])

In [94]:
a

array([2, 4, 6, 8])

In [92]:
type(a)

numpy.ndarray

In [93]:
len(a)

4

In [97]:
a.dtype #extraemos el tipo de los valores contenidos en ese array

dtype('int64')

In [96]:
#un array numpy solo permite UN TIPO DE DATO

In [99]:
a.ndim #number of dimentions

1

In [102]:
a.shape #nos devuelve una tupla, conteniendo para cada dimensión el número de elementos en dicha dimensión
#el output me muestra que hay 4 elementos en la única dimensión

(4,)

Lo mas importante:
1. Exraer datos de un array
2. Aplicar funciones a un array

### Array bidimensional

In [105]:
b = np.array([[2, 4, 6], [1, 2, 3]])
b

array([[2, 4, 6],
       [1, 2, 3]])

In [107]:
b.dtype #enteros de 64bits

dtype('int64')

In [109]:
b.ndim #2 dimensiones

2

In [111]:
b.shape #2 filas, 3 columnas. primero en vertical, despues en horizonal. 2 dimensiones de 3 valores

(2, 3)

In [114]:
np.arange(2, 7) #me devuelve una rray numpy unidimensional del 2 hasta el 6

array([2, 3, 4, 5, 6])

In [119]:
np.arange(7) #desde el 0 al 7, sin incluir el último

array([0, 1, 2, 3, 4, 5, 6])

In [118]:
np.arange(10, 23, 3) #del 10 al 23, de 3 en 3

array([10, 13, 16, 19, 22])

In [122]:
np.linspace(10, 20, 6) #

array([10., 12., 14., 16., 18., 20.])

In [126]:
np.linspace(10, 20, 17)

array([10.   , 10.625, 11.25 , 11.875, 12.5  , 13.125, 13.75 , 14.375,
       15.   , 15.625, 16.25 , 16.875, 17.5  , 18.125, 18.75 , 19.375,
       20.   ])

In [125]:
names(random)

['BPF', 'LOG4', 'NV_MAGICCONST', 'RECIP_BPF', 'Random', 'SG_MAGICCONST', 'SystemRandom', 'TWOPI', 'betavariate', 'choice', 'choices', 'expovariate', 'gammavariate', 'gauss', 'getrandbits', 'getstate', 'lognormvariate', 'normalvariate', 'paretovariate', 'randbytes', 'randint', 'random', 'randrange', 'sample', 'seed', 'setstate', 'shuffle', 'triangular', 'uniform', 'vonmisesvariate', 'weibullvariate']


In [124]:
names(np.random)

['BitGenerator', 'Generator', 'MT19937', 'PCG64', 'PCG64DXSM', 'Philox', 'RandomState', 'SFC64', 'SeedSequence', 'beta', 'binomial', 'bit_generator', 'bytes', 'chisquare', 'choice', 'default_rng', 'dirichlet', 'exponential', 'f', 'gamma', 'geometric', 'get_bit_generator', 'get_state', 'gumbel', 'hypergeometric', 'laplace', 'logistic', 'lognormal', 'logseries', 'mtrand', 'multinomial', 'multivariate_normal', 'negative_binomial', 'noncentral_chisquare', 'noncentral_f', 'normal', 'pareto', 'permutation', 'poisson', 'power', 'rand', 'randint', 'randn', 'random', 'random_integers', 'random_sample', 'ranf', 'rayleigh', 'sample', 'seed', 'set_bit_generator', 'set_state', 'shuffle', 'standard_cauchy', 'standard_exponential', 'standard_gamma', 'standard_normal', 'standard_t', 'test', 'triangular', 'uniform', 'vonmises', 'wald', 'weibull', 'zipf']


In [129]:
np.random.randint(4, 14) #nº aleatorio entre 4 y 14.

6

In [130]:
np.random.randint(4, 14, 7) #nº aleatorio entre 4 y 14, y un tamaño de 7 nºs aleatorios

array([ 7,  8, 10,  7, 11, 11,  9])

In [137]:
np.random.randint(4, 14, size = (3, 5)) #nº aleatorio entre 4 y 14, y un tamaño de 2 dimensiones

array([[10,  9,  6, 11, 13],
       [10, 13,  9,  9, 12],
       [10,  7,  8,  9,  4]])

In [133]:
#Primera dimensión o eje cero, es el eje vertical
#Segunda dimensión en el eje uno, es el eje horizontal

In [138]:
np.random.randint(4, 14, size = (3, 4, 2)) #nº aleatorio entre 4 y 14, y un tamaño de 3 dimesiones

array([[[ 9, 11],
        [ 8,  9],
        [ 6,  6],
        [ 7,  4]],

       [[12,  8],
        [13, 10],
        [ 8,  7],
        [ 4,  6]],

       [[ 7,  8],
        [ 4,  5],
        [ 4, 10],
        [ 7,  6]]])

In [136]:
#Primera dimensión o eje cero, es el eje vertical
#Segunda dimensión en el eje uno, es el eje horizontal
#Tercera dimensión en el eje dos, es el eje de profundidad

In [141]:
np.random.random(size = (5, 3)) #2 dimensiones. 5 filas, 3 columnas.

array([[0.51882169, 0.6939915 , 0.66090873],
       [0.52142573, 0.85822642, 0.11894412],
       [0.77479823, 0.93610834, 0.85907581],
       [0.89251292, 0.75301437, 0.91907648],
       [0.08717475, 0.43315327, 0.98672659]])

In [144]:
a = np.arange(24) #me devuelve un array unidimensional
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [147]:
a.shape

(24,)

In [152]:
a.reshape((4, 6)) #aca a una variable unidimensional, le agregamos una segunda dimensión
#esto me genera un array nuevo. "a" no cambia

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [154]:
#a.reshape((3, 17)) #esto no funcionaria, porque el total no da los 24 elementos originales de "a"

In [157]:
np.reshape(a, (2, 12)) # o np.reshape(a, new = (4, 6))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [158]:
np.reshape(a, (3, 4, 2))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [159]:
np.reshape(a, (24, 1))

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [163]:
a #array unidimensional Solo valores en un eje

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [164]:
a.reshape((1, 24)) #array bidimensional aunque sea una sola fila, pero de 24 valores. Y necesita dos valores. Es bidimensional

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23]])

In [166]:
a = np.arange(24) #unidimensional
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [167]:
a.reshape((1, 24)) #transforme a en dos dimensiones

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23]])

In [169]:
a.reshape((24, 1)) #transforme a en dos dimensiones

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [172]:
a.reshape(1, 24, 1) #transforma a en tres dimensiones

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]]])

# Selección de valores

In [174]:
a = np.arange(10, 16)
a

array([10, 11, 12, 13, 14, 15])

In [176]:
a[0]

10

In [178]:
a[-1]

15

In [181]:
a[2:4]

array([12, 13])

In [182]:
a[-4:4]

array([12, 13])

In [183]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [184]:
a[7:2:-1]

array([7, 6, 5, 4, 3])